set(WAVELENGTH_GAME_SRCS
    avatarpartset.cpp
    axetrack.cpp
    axetrackcontourbuilder.cpp
    axetrackdata.cpp
    axetrackharmonybuilder.cpp
    backmusic.cpp
    backmusicbuilder.cpp
    bankloader.cpp
    bankloaderbuilder.cpp
    catchtrackbuilder.cpp
    catchtrackdata.cpp
    catchtrackdisplay.cpp
    changesectionevent.cpp
    controllerdisplay.cpp
    difficultyrating.cpp
    duel.cpp
    duellogic.cpp
    duelpattern.cpp
    dueltrack.cpp
    dueltrackpitcher.cpp
    forcefeedbackmgr.cpp
    forcefeedbackmgrcontroller.cpp
    forcefeedbackmgrmotoreffect.cpp
    game.cpp
    gameconfig.cpp
    gamelogic.cpp
    gametrackselector.cpp
    gemcatcher.cpp
    gemcursor.cpp
    gemslice.cpp
    guideticker.cpp
    helptext.cpp
    inputmap.cpp
    inputmgr.cpp
    joypadps2.cpp
    juicemeter.cpp
    lineartransform.cpp
    localplayer.cpp
    lyric.cpp
    mixer.cpp
    multigamelogic.cpp
    netarbiter.cpp
    netfaker.cpp
    padrecord.cpp
    pitchtrack.cpp
    pitchtrackbuilder.cpp
    pitchtrackdisplay.cpp
    pitchtrackgems.cpp
    pitchtrackmusic.cpp
    pitchtrackplaygems.cpp
    pitchtrackriffdata.cpp
    pitchtrackriffs.cpp
    player.cpp
    playerprofile.cpp
    playmap.cpp
    playnoteevent.cpp
    points.cpp
    rateaverager.cpp
    remix.cpp
    remixhud.cpp
    remixtutorial.cpp
    remoteplayer.cpp
    rotateevent.cpp
    scratchtrack.cpp
    scratchtrackbuilder.cpp
    scratchtrackdata.cpp
    scripttask.cpp
    scripttrackbuilder.cpp
    scripttrackdata.cpp
    sectionboundaries.cpp
    slotgrid.cpp
    sologamelogic.cpp
    stats.cpp
    streamqueue.cpp
    streamtask.cpp
    stutter.cpp
    trackcapturer.cpp
    track.cpp
    trackselector.cpp
    tutorialgamelogic.cpp
    voxtrack.cpp
    voxtrackdisplay.cpp
    voxtrackmusic.cpp
    waitfortasktask.cpp
    waitinteractiveremixtask.cpp
    waitinteractivetask.cpp
    waittimetask.cpp
    world.cpp
    worldlogic.cpp
    worldmgr.cpp)

add_library(wavelength_game STATIC ${WAVELENGTH_GAME_SRCS})
target_link_libraries(wavelength_game PRIVATE wavelength_common)
