set(WAVELENGTH_MEMCARD_SRCS
    mccardstatustask.cpp
    mccheckremixspaceneededtask.cpp
    mcchecksavespaceneededtask.cpp
    mcclosetask.cpp
    mccreatesavedirtask.cpp
    mcdeletefreqtask.cpp
    mcdeleteremixtask.cpp
    mcdeletesavedremixtask.cpp
    mcdeletetask.cpp
    mcfindremixtask.cpp
    mcformatcardtask.cpp
    mcformattask.cpp
    mcgetallremixinfostask.cpp
    mcgetdirtask.cpp
    mcgetinfotask.cpp
    mcgetremixdatatask.cpp
    mcgetremixinfotask.cpp
    mcgetremixnamestask.cpp
    mcinitialchecktask.cpp
    mclistnetconfigstask.cpp
    mclistremixestask.cpp
    mcloadfiletask.cpp
    mcloadfreqfilestask.cpp
    mcloadfreqstask.cpp
    mcloadremixtask.cpp
    mcloadsettingstask.cpp
    mcmanager.cpp
    mcmkdirtask.cpp
    mcnetconfigtask.cpp
    mcopencurrremixtask.cpp
    mcopentask.cpp
    mcreadtask.cpp
    mcsavedatatask.cpp
    mcsavefiletask.cpp
    mcsavefreqtask.cpp
    mcsaveremixtask.cpp
    mcsavesettingstask.cpp
    mcseektask.cpp
    mcunformatcardtask.cpp
    mcunformattask.cpp
    mcwritetask.cpp
    memcard.cpp
    memcardconfig.cpp
    memcardserialtask.cpp
    memcardtask.cpp
    shiftjis.cpp)

add_library(wavelength_memcard STATIC ${WAVELENGTH_MEMCARD_SRCS})
target_link_libraries(wavelength_memcard PRIVATE wavelength_common)
