set(WAVELENGTH_RND_SRCS
    amovieset.cpp
    animatable.cpp
    arena.cpp
    blur.cpp
    bufstream.cpp
    button.cpp
    cam.cpp
    collideable.cpp
    dmapacket.cpp
    drawable.cpp
    drawverts.cpp
    environ.cpp
    filestream.cpp
    font.cpp
    generator.cpp
    keychannel.cpp
    light.cpp
    lightanim.cpp
    lodmesh.cpp
    manager.cpp
    mat.cpp
    matanim.cpp
    memstream.cpp
    mesh.cpp
    meshanim.cpp
    movie.cpp
    multimesh.cpp
    object.cpp
    particlesys.cpp
    particlesysanim.cpp
    pscam.cpp
    psenviron.cpp
    psmat.cpp
    psmesh.cpp
    psmultimesh.cpp
    psparticlesys.cpp
    pstex.cpp
    raytest.cpp
    rndanimatable.cpp
    rndcam.cpp
    rndcollideable.cpp
    rnddrawable.cpp
    rndmanager.cpp
    rndmat.cpp
    rndmatanim.cpp
    rndmesh.cpp
    rndmeshanim.cpp
    rndobject.cpp
    rndrenderer.cpp
    rndtex.cpp
    rndtransanim.cpp
    rndtransformable.cpp
    stream.cpp
    string.cpp
    text.cpp
    transanim.cpp
    transformable.cpp
    tunnel.cpp
    tunnelevent.cpp
    tunnelseeker.cpp
    tunnelseeksection.cpp
    tunnelseekstrip.cpp
    view.cpp)

add_library(wavelength_rnd STATIC ${WAVELENGTH_RND_SRCS})
target_link_libraries(wavelength_rnd PRIVATE wavelength_common)
