#pragma once

#define IDS_SYNTHEDIT 1
#define IDD_ABOUTBOX_SYNTHEDIT 1
#define IDB_SYNTHEDIT 1
#define IDI_ABOUTDLL 1
#define IDS_SYNTHEDIT_PPG 2
#define IDS_SYNTHEDIT_PPG_CAPTION 200
#define IDD_PROPPAGE_SYNTHEDIT 200
#define IDD_INTDIALOG 201
#define IDC_EDIT1 201
