set(WAVELENGTH_RNDARTT_SRCS
    abitmap.cpp
    abmpfile.cpp
    acanvas.cpp
    acanvas15.cpp
    acanvas24.cpp
    acanvas32.cpp
    acanvas8.cpp
    acanvaslin15.cpp
    acanvaslin24.cpp
    acanvaslin32.cpp
    acanvaslin4.cpp
    acanvaslin8.cpp
    afix.cpp
    agfxfile.cpp
    agiffile.cpp
    apalette.cpp
    apolygon.cpp
    arect.cpp
    arle8reader.cpp
    atgafile.cpp
    normalkey.cpp)

add_library(wavelength_rndartt STATIC ${WAVELENGTH_RNDARTT_SRCS})
target_link_libraries(wavelength_rndartt PRIVATE wavelength_common)
